/** Add your relevant code here for the issue to reproduce */
import Image from "next/image";

export default function Home() {
  return <div>
    <p>This is the wanted result</p>
    <NormalImage />
    <p>This is the attempted way</p>
    <ImageNext />
    <p>This is the workaround</p>
    <ImgTagDirectNext />
  </div>
}

// Image Generated by https://github.com/jstrieb/github-stats
// Added Both '#gh-dark-mode-only' to src

export const NormalImage = () => {
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      fetchPriority="high"
      alt="Chart of Programming Languages, Normal Image"
      src="/languages.svg#gh-dark-mode-only"
    />
  );
};

export const ImgTagDirectNext = () => {
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      fetchPriority="high"
      alt="Chart of Programming Languages, Next Image Directly"
      src="/_next/image?url=%2Flanguages.svg&w=750&q=75#gh-dark-mode-only"
    />
  );
};

export const ImageNext = () => {
  return (
      <Image  
          fetchPriority="high"
          alt="Chart of Programming Languages, Attempt with Next/Image" 
          src="/languages.svg#gh-dark-mode-only"
          width={360}
          height={210}
      />

      // Results in url:
      // /_next/image?url=%2Flanguages.svg%23gh-dark-mode-only&w=750&q=75
  );
};